// <auto-generated/>

#pragma warning disable
#nullable enable

using System.Runtime.CompilerServices;
using static System.AttributeTargets;

#if !NET6_0_OR_GREATER
namespace System.Diagnostics {

    [AttributeUsage(Class | Method | Constructor | Struct, Inherited = false)]
    internal sealed class StackTraceHiddenAttribute : Attribute { }

}
#endif

#if !NET5_0_OR_GREATER
namespace System.Runtime.CompilerServices {

    internal static class IsExternalInit { }

    [AttributeUsage(Module | Class | Struct | Interface | Constructor | Method | Property | Event, Inherited = false)]
    internal sealed class SkipLocalsInitAttribute : Attribute { }

}
#endif

#if !NET6_0_OR_GREATER
namespace System.Runtime.CompilerServices {

    [AttributeUsage(Parameter, Inherited = false)]
    internal sealed class CallerArgumentExpressionAttribute : Attribute {
        public CallerArgumentExpressionAttribute(string parameterName) {
            ParameterName = parameterName;
        }

        public string ParameterName { get; }
    }

}
#endif

#if !NET7_0_OR_GREATER
namespace System.Diagnostics.CodeAnalysis {

    [AttributeUsage(Constructor, Inherited = false)]
    internal sealed class SetsRequiredMembersAttribute : Attribute { }

    [AttributeUsage(Method | Property | Parameter, Inherited = false)]
    internal sealed class UnscopedRefAttribute : Attribute { }

}

namespace System.Runtime.CompilerServices {

    [AttributeUsage(All, AllowMultiple = true, Inherited = false)]
    internal sealed class CompilerFeatureRequiredAttribute : Attribute {
        public CompilerFeatureRequiredAttribute(string featureName) {
            FeatureName = featureName;
        }

        public string FeatureName { get; }
        public bool   IsOptional  { get; init; }
    }

}
#endif

#if !NET6_0_OR_GREATER
namespace Metriks {

    static partial class ArgumentNullExceptionPolyfill {
        extension(ArgumentNullException) {
            internal static void ThrowIfNull([NotNull] object? argument, [CallerArgumentExpression(nameof(argument))] string? paramName = null) {
                if (argument is null) {
                    throw new ArgumentNullException(paramName);
                }
            }
        }
    }

}
#endif

#if !NET8_0_OR_GREATER

namespace Metriks {

    static partial class ArgumentOutOfRangeExceptionPolyfill {
        extension(ArgumentOutOfRangeException) {
            internal static void ThrowIfNegative(int value, [CallerArgumentExpression(nameof(value))] string? paramName = null) {
                if (value < 0) {
                    throw new ArgumentOutOfRangeException(paramName, value, "Value must be non-negative.");
                }
            }
        }
    }

}

#endif