name: Publish Metriks to NuGet

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      SolutionName: ./Metriks.sln
      ProjectPath: ./Src/Metriks.csproj
      TestProjectPath: ./Tests/Tests/Metriks.Tests.csproj
      NugetOutputDir: ./nupkg/
            
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore ${{ env.ProjectPath }}

      - name: Build project
        run: dotnet build ${{ env.ProjectPath }} --configuration Release --no-restore

      - name: Restore Test dependencies
        run: dotnet restore ${{ env.TestProjectPath }}

      - name: Build Test project
        run: dotnet build ${{ env.TestProjectPath }} --configuration Release --no-restore

      - name: Run Test project
        run: dotnet test ${{ env.TestProjectPath }} --configuration Release --no-restore
      
      - name: Pack
        run: dotnet pack ${{ env.ProjectPath }} --configuration Release --no-build --output ${{ env.NugetOutputDir }}

      - name: Push to NuGet
        run: |
          Get-ChildItem ${{ env.NugetOutputDir }}*.nupkg -Exclude *.symbols.nupkg | ForEach-Object {
            dotnet nuget push $_.FullName --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
          }
        shell: pwsh